### ISSUE TITLE
Depth Lines Checkbox remains checked on Reset All

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/density-buoyancy-common#188]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1095, the Depth Lines Checkbox on the first 3 screens starts off unchecked by default. Checking the box and then pressing Reset All doesn't restore the default setting. 

**Steps to reproduce**
1. On any of the first 3 screens, check the Depth Lines checkbox
2. Press Reset All

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Buoyancy‬
URL: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.9/phet/buoyancy_all_phet.html
Version: 1.0.0-dev.9 2024-06-12 15:13:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 1380x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
I'll work on this

**Comment by samreid** [comment]
Fixed, closing.

**Comment by Nancy-Salpepi** [comment]
While testing https://github.com/phetsims/density-buoyancy-common/issues/197 I noticed that this is still broken.

**Comment by zepumph** [comment]
I was able to reproduce easily

**Comment by zepumph** [comment]
I think the regression happened over in #186. Should be fixed now.

**Comment by Nancy-Salpepi** [comment]
Fixed on main. 
Closing.
